import type { Metadata } from "next";
import "./globals.css";


 const metadata: Metadata = {
  title: "Innovate Home#10",
  description: "Generated by create Md Kamruzzaman",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) =>{
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
 export default RootLayout;